export { default as HomePage } from "./HomePage/HomePage";
export { default as BookingPage } from "./BookingPage/BookingPage";
export { default as ContactPage } from "./ContactPage/ContactPage";
export { default as UserProfileManagement } from "./UserProfileManagement/UserProfileManagement";
export { default as BookingsManagement } from "./BookingsManagement/BookingsManagement";
export { default as RestaurantManagementPortal } from "./RestaurantManagementPortal/RestaurantManagementPortal";
export { default as UsersManagement } from "./UsersManagement/UsersManagement";
export { default as TablesManagement } from "./TablesManagement/TablesManagement";
export { default as MenuManagement } from "./MenuManagement/MenuManagement";
export { default as MenuPage } from "./MenuPage/MenuPage";
export {default as CartPage } from "./CartPage/CartPage";
export { default as KitchenPage } from "./KitchenPage/KitchenPage";